### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Blakekug13** [geode-sdk/android-launcher#35]
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN11GameManager9reloadAllEbbbb" referenced by "/data/data/com.geode.launcher/files/copied/Geode.so"...
	at java.lang.Runtime.load0(Runtime.java:933)
	at java.lang.System.load(System.java:1729)
	at com.geode.launcher.GeometryDashActivity.t(SourceFile:47)
	at com.geode.launcher.GeometryDashActivity.v(SourceFile:615)
	at com.geode.launcher.GeometryDashActivity.onCreate(SourceFile:172)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8270)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by hiimjustin000** [comment]
Outdated Geometry Dash it seems

**Comment by matcool** [comment]
outdated gd.
